Day1 files
takumi-yamazaki-git/Dojo-2023 pull request #1
Opened 2023-06-13 04:44 UTC by takumi-yamazaki-git

HTML/CSSの１日目の課題を提出します。
主にCSSにメモのコメントをつけています。
ご確認お願いします。

2023-06-13 09:47 UTC, natsukiyamada commented on task1.css
> +}
ここの`width: 100%`と`text-align: center`についてですが、
`.office`, `garoon`, `.mailwise`classでも同じプロパティと値ですね！
共通化してみてください～

2023-06-13 09:53 UTC, natsukiyamada commented on task1.css
> +  margin: 30px auto 30px auto; /* マージン（余白）　左から　上　右　下　左 */
こちらも[上記のコメント](https://github.com/takumi-yamazaki-git/Dojo-2023/pull/1/commits/e52c1273327f4a4ad1baf95d38927e181bffe0cd#r1227851063)と同じで、
各画像にに対して適用している`width: 80%`と` margin: 30px auto 30px auto; `は共通化できますね。

2023-06-13 09:54 UTC, natsukiyamada requested changes
レビューしたので確認お願いします～

2023-06-13 10:05 UTC, natsukiyamada commented on task1.html
> +        <img src="./image-kn.png" alt="kintone製品紹介画像">
レビュー後ですみません。追記です。

ファイル構成についてですが、画像用のディレクトリを作成して
その中にpngファイルをいれた方が見やすいですね。対応するかどうかはおまかせします！
以下のようなイメージです。
```
task1
  | - image
  |    | -  Garoon.png
  |    | -  kintone.png
  |    | -  mailwise.png
  |    | -  office.png
  | 
  | - task1.css
  | - task1.html

```

2023-06-14 01:19 UTC, takumi-yamazaki-git commented
レビューありがとうございます。
ファイルに修正をくわいたものをver2としてアップロードしました。
主な変更点は以下です。
* .htmlファイルにクラスcontainer2 container3を追加
* .cssファイル冒頭に.container2 .container3に関する記述を追記
* 追記に合わせ.cssファイルの色以外の設定を削除

また、ディレクトリ構造については**今のところ変更はしていません**が、
画像のみのディレクトリを作って整理したほうがよいということについては理解しました。
丁寧に解説していただきありがとうございます！

2023-06-14 05:11 UTC, natsukiyamada commented on task1_ver2.css
> +
いい感じに共通化できてますね！

2023-06-14 05:13 UTC, natsukiyamada commented on task1_ver2.html
> +        <!-- ここに記載する -->
`contatiner2`と`container3`の命名についてですが、
この名前を見ただけだと何をするクラスかわかりにくいので
分かりやすくなるように変更してみてください！
「他のエンジニアがこのクラス名を見て意味を理解しやすいか？」という観点から考えてみるといいと思います！

2023-06-14 05:14 UTC, natsukiyamada requested changes
レビューしたので確認お願いします～

2023-06-14 05:33 UTC, takumi-yamazaki-git commented
ファイル修正しました！
ver2 からの変更点は以下です。
* container2->addpageinfo に変数を変更
* container3->imgsizesetter に変数を変更

いずれも変数名のみの変更です。cssにも反映してあります。

ご確認お願いします。

2023-06-15 03:26 UTC, natsukiyamada commented on task1_ver3.css
> +
OKです！
補足ですが、htmlの命名規則として以下のような記事が参考になると思います。
https://ssaits.jp/promapedia/method/bem.html#

2023-06-15 03:26 UTC, natsukiyamada approved these changes
課題OKです！お疲れ様です！

2023-06-15 03:26 UTC, merged