Day9_files
takumi-yamazaki-git/Dojo-2023 pull request #11
Opened 2023-06-26 02:12 UTC by takumi-yamazaki-git

# task9のファイルを提出します。
ご確認お願いします。

## コードチェック時にフリーズ再発
コードの57行目から71行目にかけて、コードチェックのサイトにコピペするとサイトがフリーズしてしまいます。
（中間課題と似たような現象）
そのため、一部;のミスなどを見逃している可能性があります。ある程度自分でも確認はしたのですが、書式のミスなどがあればコメントお願いします。

2023-06-26 02:13 UTC, takumi-yamazaki-git commented
ver1.1修正
一部コメントアウトの箇所を修正しました。

2023-06-26 10:37 UTC, natsukiyamada commented on task9.js
> +//      if (window.confirm(`${checkrepeat(saveevent.record.重複禁止項目.value,getList)}件のレコードと重複しています。\nこのまま保存しますか？`) === false) {
コメント削除おねがいします！

2023-06-26 10:48 UTC, natsukiyamada commented on task9.js
> +    const getValues = await kintone.api(kintone.api.url('/k/v1/records.json'), 'GET', saveParam);
以下修正お願いします！

現状全てのレコードを取得してきていますが、
queryパラメーターsaveParamに入れてしまえば簡潔に実装できると思います！
参考：https://cybozu.dev/ja/kintone/docs/rest-api/records/get-records/#request

queryパラメーターを使って「全ての既存レコードのうち、現在編集画面で入力している重複禁止項目と値が一致するレコード」というように指定すればいいかなと思います！

2023-06-26 10:56 UTC, natsukiyamada commented on task9.js
> +  });
以下確認です！空いた時間に返信していただけると嬉しいです~

48行目~55行目までのイベントはいらないかな~と思うのですがどうでしょうか。
課題9用のアプリテンプレートがあったと思うのですが、サイボウズ製品フィールドと管理番号フィールドに
値を入れると自動で値が挿入される仕様になっています。なのでJSカスタマイズで値を自動挿入しなくてもいいはず..
（課題7で使ったアプリをそのまま使用しているなら、課題9用のアプリテンプレートを使ってください~）

2023-06-26 11:00 UTC, natsukiyamada requested changes
レビューしました！
確認お願いします~

2023-06-27 01:43 UTC, takumi-yamazaki-git commented
課題修正しました！
クエリを使って処理を簡潔に書いたり、イベントリストを整理し必要最低限のイベントのみを記述したりなど全体的にコードが短くなるよう修正しました。

コメントにありました48行目から55行目までのイベントについてですが、値を確認するときに重複禁止項目をconsole.logを使うと、一つ和えの入力値を反映してしまうという現象が起きていました。
これに対応するため、入力た値と表示する値が同じに見えるよう、都度更新処理を行っていました。
しかし今回の課題の場合、「保存ボタンを押す」という工程でイベントが更新され、フィールドを再読み込みするので実際に入力されている値とJSで読み込まれる値に差異がなくなるため、これら一連のイベントを削除しました。

2023-06-27 03:38 UTC, natsukiyamada commented on task9.js
> +    await kintone.app.record.setFieldShown('重複禁止項目', false);
以下相談事項です！

15行目の処理について、これは「重複禁止項目フィールドを非表示にする」処理だと思うのですが、
これは課題9の要件に入ってなかったと思います。山崎さんの方でも確認してもらっていいでしょうか..
要件に入ってなかったらこのイベントは削除お願いしたいです！

2023-06-27 03:41 UTC, natsukiyamada commented on task9.js
> +    const param = {app: 32,fields: ['重複禁止項目'], query: '重複禁止項目 = "' + chValue + '"'};
以下修正お願いします！

param内の`app`プロパティの値は32と指定していますが、
ここはイベントからアプリのIDを取得するとよいと思います。
https://cybozu.dev/ja/kintone/docs/js-api/app/get-app-id/

2023-06-27 03:46 UTC, natsukiyamada commented on task9.js
> +    const getValuesquery = await kintone.api(kintone.api.url('/k/v1/records.json'), 'GET', param);
以下修正お願いします！

一部キャメルケースになっていない変数があるので修正お願いします~
→`getValuesquery`、`saveevent`

2023-06-27 03:48 UTC, natsukiyamada requested changes
レビューしました！確認お願いします！

2023-06-27 04:13 UTC, takumi-yamazaki-git commented
レビューいただいた部分について編集しました。
自動計算フィールドの非表示については、課題要件の解釈ミスによるものでした。
どういうわけか
「標準機能の重複禁⽌は外したい」を「重複禁止項目を非表示にしたい」
と勘違いしてし舞いました…

2023-06-27 04:47 UTC, natsukiyamada approved these changes
実装めっちゃシンプルになりましたね！課題OKです！
おつかれさまです！

2023-06-27 04:56 UTC, merged