mid_basic
takumi-yamazaki-git/Dojo-2023 pull request #8
Opened 2023-06-21 04:24 UTC by takumi-yamazaki-git

2023-06-21 04:30 UTC, takumi-yamazaki-git commented
コメント書き忘れました
**中間課題最低限の要件を実装しました**
現在はソートなどチャレンジ課題に取り組んでいます。
現時点で修正するポイントなどがあればコメント音w買いします。

以下補足です。
* 変数のに _ を使っているものと小文字+大文字のものが混ざっていますが、_のあるものはHTML要素に関する変数、小文字＋大文字のものはJSで完結する変数を表しています。
* .htmlファイルの55行目のコメントを外すと、要素数が5から3に減ります。取得した値によってCSSが崩れないかを検証するために残しています。(課題の必須要件にあり)

2023-06-21 05:14 UTC, takumi-yamazaki-git commented
# チャレンジ課題提出
すべての要件を満たしたコードを_allとしてアップしましたので、ご確認お願いします。
参照しているcssファイルはtask5.cssで変わりません。
レビューはtask5.htmlではなく**task5_all.html**のファイルに対して行っていただけると嬉しいです。
よろしくお願いします。

2023-06-21 05:28 UTC, takumi-yamazaki-git commented
ver2修正
一部残っていたconsole.logを削除しました。
* エラー時はわかりやすくするためにconsole.log()でエラー表示をしています。

ver3修正
エラーメッセージのPタグ出力を削除しました
（検証を行いにくく、APIのエラーが発生しているのにさらにHTML出力によりエラーが発生してしまうリスクを避けるため）
コンソールログにはエラーメッセージを出したままにしています。

2023-06-21 09:21 UTC, natsukiyamada commented on task5_all.html
> +      const tablecreator = (day, cate, con, url, targ) => {
以下は修正判断はお任せします！

- 引数は短くすると返ってわかりにくくなっちゃうのでそのままでいい気がします。
例えば`cate`であれば`category`等でいいかなと思いました！
※変数名が長すぎる場合は省略するかな~という感じですね。

2023-06-21 09:21 UTC, natsukiyamada commented on task5_all.html
> +        let td_ele = document.createElement('td');
以下変更お願いします！

`td_ele`は新たな<td>エレメントを作るために何度も再利用されていますが、同じ変数に違う値が何度も挿入されるのは避けたいです！ 新しい変数を定義した方がいいかなと思います！以下のようなイメージですね。

```
const td_day = document.createElement('td');
td_day.textContent = day;
tr_ele.appendChild(td_day);

const td_category = document.createElement('td');
td_category.textContent = cate;
// ...カテゴリによるidの設定
tr_ele.appendChild(td_category);

const td_content = document.createElement('td');
// ...a要素の作成と設定
td_content.appendChild(url_ele);
tr_ele.appendChild(td_content);

```

2023-06-21 09:21 UTC, natsukiyamada commented on task5_all.html
> +            td_ele.id = 'product';
以下変更お願いします！

htmlのidは一意の値になることが望ましいです。
`tablecreater`関数を何度も呼び出すとidに一意にならないので, classを使う等して変更お願いします！

2023-06-21 09:22 UTC, natsukiyamada commented on task5_all.html
> +        con = strChanger(con);
以下変更お願いします！

`strChanger`関数によって`con`の内容が変わっている可能性があります。
ここは変数定義していいと思いました。（`const formattedCon = ...`みたいな感じです）

2023-06-21 09:22 UTC, natsukiyamada commented on task5_all.html
> +        addNews.appendChild(tr_ele);
以下変更お願いします！

変数宣言をせず`addNews`に直接appendChildするのではなく、明示的に取得した方が見やすいと思います。（どのように宣言されたのかが明らかでないと、後でコードを読む人がわからなくなってしまう可能性があります！）

なので、以下のように変数宣言してあげると見やすくなると思います！
```
const addNews = document.getElementById('addNews');

```



また、

2023-06-21 09:22 UTC, natsukiyamada commented on task5_all.html
> +        for (let tableDisp = 0; tableDisp < reps.data.length; tableDisp++) {
以下修正お願いします！

- tableDisp変数がforループのカウンターとして使われていますが、特別何か役割がある変数ではないので、より一般的なiやindex等でいいと思います！

2023-06-21 09:23 UTC, natsukiyamada commented on task5_all.html
> +        console.log('エラーが発生しました');
以下修正判断お任せします！

81行目についてですが、ユーザー側にエラーが発生したことを伝えたいのであれば、
画面上に出力すべきだと思いました！
※`window.alert()`等は使うとよさそうです！

2023-06-21 09:25 UTC, natsukiyamada requested changes
レビューしたので確認お願いします~

※task5.htmlはtask5_all.htmlに包含されているので削除してしまって大丈夫です！
次の修正時に削除おねがいします！

2023-06-22 03:02 UTC, takumi-yamazaki-git commented
コード修正しました！
変数名の変更・追加の変数定義・アラート表示など、基本的には指摘いただいた部分をそのまま直しています。
また、idからclassに直すにあたりcssファイルを一部 (#と.)編集しています。

ご確認よろしくお願いします。

2023-06-22 05:56 UTC, natsukiyamada commented on task5_all.html
> +        const url_ele = document.createElement('a');
以下修正の判断お任せします！

ちょっと細かいですが、`url_ele`は46行目で初めて使っているので、宣言位置を45行目付近に持ってくると可読性が高まります！そうすると誰かがレビューする際、`url_ele`を記憶する時間が短くなるので可読性が高まっていい感じになります！

2023-06-22 06:12 UTC, natsukiyamada commented on task5.html
> +      const tablecreator = (day, cate, con, url, targ) => {
以下補足です！（修正は特にしなくても大丈夫です！次から意識してもらえばと思います）

プルリクを出してくださった際、
>変数のに _ を使っているものと小文字+大文字のものが混ざっていますが、_のあるものはHTML要素に関する変数、小文字＋大文字のものはJSで完結する変数を表しています。

と記載してくださいましたが、基本JSの変数定義ではキャメルケースを使うことが多いです。
例えば、HTMLの<td>要素を参照するJavaScriptの変数名としては、tdElementのように命名するのが一般的です。

※いずれにしても、コード全体で一貫した命名規則を採用することが、エンジニア間で共通認識が取れるという意味で重要です というコメントでした🙇‍♂️

2023-06-22 06:13 UTC, natsukiyamada reviewed
レビューしました！
確認お願いします~

2023-06-23 01:05 UTC, takumi-yamazaki-git commented
変数名・変数宣言位置・awaitの修正をしました。
88行目にawaitを置くことで、その後に同関数内でcondole.logなどを実行した時も先にAPIを読み込んで一連の処理が終わってから出力されることを確認しました。
(例　89行目にconsole.logで何か出力しようとした場合、88行目の処理が終わるまで待ってくれました 88行目にawaitをつけない場合、89行目のconsole.logが先に処理されました。)
…が、API読み込みを参照して別の処理を行うときはともかく、今回は同じ関数内でページ出力までのすべての処理を行っているので、awaitしても意味があるのか、若干わかっていない部分があります。
言語化が難しいので、また定例ミーティングで質問させてください！

2023-06-26 07:04 UTC, takumi-yamazaki-git commented
# 進捗状況
## ファイルの一部を修正しました。
* switch文にdefault値を設定し、新たにクラスを設定しました。
* これに合わせ、CSSで新たなクラスを定義しました。（基本使いません）
* 関数の名前を変更しました。
* APIを使用した時のthenの処理の一部を関数化して書式を移動しました。

## then chatchを使わない処理について
いろいろと検証中です。
APIを使用した時はプロミスオブジェクトが返ってくることが多く、このオブジェクトの取り扱いに苦戦しています。
ただreturnするだけではundifindになり、その後の処理ができなくなってしまうのですが、かといってthen内で扱いやすい形に変更を加えるとコードが長くなり、結果現在のような形に戻ってしまうため扱いに悩んでいるのが現状です。

2023-06-29 08:11 UTC, natsukiyamada commented on task5_all.html
> +      const apiUrl = 'https://54o76ppvn8.execute-api.ap-northeast-1.amazonaws.com/prod/bb-dojo';
以下修正お願いします！

apiUrlは80行目でしか使っていないので、80行目付近に移動させてください～

2023-06-29 08:13 UTC, natsukiyamada commented on task5_all.html
> +        }
以下修正お願いします！

この部分も関数化できると思います！
長い処理なので分かりやすくまとめてほしいです！

2023-06-29 08:13 UTC, natsukiyamada commented on task5_all.html
> +        urlEle.innerText = formattedcontent;
以下修正お願いします！

formattedcontentはキャメルケースでお願いします！

2023-06-29 08:15 UTC, natsukiyamada commented on task5_all.html
> +          const tdtarget = obj.data[i].target.value;
以下修正お願いします！

各変数キャメルケースでお願いします！
例：`tdday`→`tdDay`

2023-06-29 08:16 UTC, natsukiyamada requested changes
レビューしました！
確認お願いします～

2023-06-30 01:01 UTC, takumi-yamazaki-git commented
一部変数名と、switch部分を関数にまとめました。
少し気になるのですが、同じ変数名を使いまわしてもいいのでしょうか。
例　30行目、73行目に「tdDay」をconstを使って呼び出していますが、前半のtdDayは挿入するためのエレメント定義、後半の変数はとってきたオブジェクトを代入して使いやすくする変数になっており、意味が結構異なっています。

2023-06-30 02:04 UTC, natsukiyamada commented on task5_all.html
> +      }
以下修正提案です！

setClassNameのswitch文では複雑な処理をしていないので、
以下のように短絡評価を使えば簡潔にかけるかな～と思います！
```
const setClassName = (getcategory) => {
  const categoryClassNames = {
    '製品': 'product',
    'IR 情報': 'ir',
    '企業情報': 'comparny',
  };

  return categoryClassNames[getcategory] || 'otherthings';
};
```
` return categoryClassNames[getcategory] || 'otherthings';`の部分は、
もし`categoryClassNames[getcategory]`が真であればcategoryClassNames[getcategory]を返し、
そうでない場合は`otherthings`を返します。

2023-06-30 02:06 UTC, natsukiyamada reviewed
レビューしました！
1点だけリファクタリングできそうな箇所があったのでコメントしています！
修正するかどうかはお任せするので、もし修正した場合はkintoneで連絡お願いします！

2023-06-30 02:13 UTC, natsukiyamada commented on task5_all.html
> +          createTable(tdDay, tdCate, tdCont, tdUrl, tdTerget);
以下修正お願いします！

>少し気になるのですが、同じ変数名を使いまわしてもいいのでしょうか。
例　30行目、73行目に「tdDay」をconstを使って呼び出していますが、前半のtdDayは挿入するためのエレメント定義、後半の変数はとってきたオブジェクトを代入して使いやすくする変数になっており、意味が結構異なっています。

確かにですね... 僕も見逃していました。質問ありがとうございます🙇‍♂️

同じ変数名が同一ファイルにあるのはよくないので変更した方がいいですね。
78行目のをtdDay変える方がいいと思います。（78行目のtdDayはHTML要素ではなくデータが入っているだけなのに対して、20行目のtdDayは実際にtd要素をcreateElementで作っているからです。）

ついでに78行目のtdDay以外の変数名も変えてもらっていいですか？？

2023-06-30 02:14 UTC, natsukiyamada requested changes
すみません、質問いただいた箇所見逃していました！
レビューしたので確認お願いします！

2023-06-30 02:48 UTC, takumi-yamazaki-git commented
課題修正しました。
分岐をオブジェクトを使って表現したり、変数名を変更したりしました。

2023-06-30 02:54 UTC, natsukiyamada requested changes
内容OKです！お疲れ様です～

2023-06-30 02:55 UTC, merged