Day7 files
takumi-yamazaki-git/Dojo-2023 pull request #9
Opened 2023-06-22 02:09 UTC by takumi-yamazaki-git

# 課題7提出
kintonedojoの課題7をアップしました。
ご確認よろしくお願いします。

2023-06-22 02:09 UTC, takumi-yamazaki-git commented
たくさんcommitしていますが、コメントアウトの削除や一部スペースのミスなどの修正を行いました。

2023-06-22 05:27 UTC, natsukiyamada commented on task7.js
> +  let imputDay = '';
以下修正お願いします！

イベント（`app.record.create.show`等）の外からimputDayの値を参照するのは避けたいです！
（現状`imputDay`を複数のイベント内で使いまわしている）

2023-06-22 05:37 UTC, natsukiyamada commented on task7.js
> +  });
以下修正お願いします！

各イベント(`app.record.create.show`等)についてですが、あまりやっている処理が変わらないので処理を共通化していいと思いました。（分けた理由などあれば教えてください~）まとめる場合以下のような感じでイベントをまとめて処理できます！

```
const events = [
'app.record.create.show',
'app.record.create.change.日付',
'app.record.create.change.サイボウズ製品',
'app.record.create.change.管理番号',
]

kintone.events.on(events, (event) => {});

```

2023-06-22 05:40 UTC, natsukiyamada commented on task7.js
> +
以下追記お願いします~

要件を見ると
>⽂字列に挿⼊するタイミングはレコード新規作成時と**レコード編集時**

と記載されているので、「レコード編集時」のイベント(`app.record.edit.show`等)も処理に含めてください~

2023-06-22 05:41 UTC, natsukiyamada requested changes
お疲れ様です！

課題レビューしたので修正お願いします~

2023-06-23 02:10 UTC, takumi-yamazaki-git commented
ファイルを修正しました。
イベントをリストに格納し、kintone.events.onで呼び出すようにしてみました。
途中switch case文があるにも関わらずbreakを入れていません。
関数内でreturnをして関数そのものを抜けているので、breakの必要がないと判断し削除しています。

以上、ご確認よろしくお願いします。

2023-06-23 02:24 UTC, natsukiyamada approved these changes
内容OKです！
変数、関数ともに適切に共通化できていて良い感じだと思います！

2023-06-26 10:29 UTC, merged